# Generated by Django 5.2.5 on 2025-08-31 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('internal_id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.CharField(help_text='External ID from the source file', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Name of the Point of Interest', max_length=255)),
                ('latitude', models.DecimalField(decimal_places=8, help_text='Latitude coordinate', max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, help_text='Longitude coordinate', max_digits=11)),
                ('category', models.CharField(help_text='Category of the Point of Interest', max_length=100)),
                ('ratings', models.JSONField(default=list, help_text='List of ratings for this PoI')),
                ('description', models.TextField(blank=True, help_text='Description of the Point of Interest', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Point of Interest',
                'verbose_name_plural': 'Points of Interest',
                'ordering': ['name'],
            },
        ),
    ]
